// list = document.querySelector('.oEbCkb');
// Array.from(list.children[0].children).map(ele => ele.children[0].children[1].children[0].children[0].innerText);
let contributor = [
    "Emmanuel Shimwa",
    "Aaron Izang",
    "Adeline Iradukunda",
    "Agertu Diriba Aliko",
    "Ahmed Khalid",
    "Ajak Chol",
    "Alliane Umutoniwase",
    "Anthony Ariik",
    "Ariette Rusaro",
    "Betelhem Chelebo",
    "Bonae Ineza",
    "Carla Batoni",
    "Celine Ishimwe",
    "Chris Hirwa",
    "Clarisse Mukayiranga",
    "David Neza Tuyishimire",
    "David Neza Tuyishimire",
    "Emmanuel Nsabagasani",
    "Emmanuel Nsabagasani",
    "Emmanuel Shimwa",
    "Enock Mugisha",
    "Evander Manna",
    "Fawziyyah Oke",
    "Fred Adossi",
    "Gabriel Tuyisingize Sezibera",
    "Gloire Gwiza",
    "Hamse Jama",
    "Hassan Luqman",
    "Hauwa Bello",
    "Heroine Mutumwinka",
    "Ivan Manzi Ya Musana",
    "Jongkuch Anyar",
    "Joshua Moses",
    "Julie Isaro",
    "Justine Neema",
    "Kadi Koita",
    "Kagame Dan",
    "Karabo Divine",
    "Karabo Ojiambo",
    "Larissa Inyange",
    "Mathew Ainomugisha",
    "Michael Nwuju",
    "Mohamed Dahab",
    "Monica Ahol",
    "Mpeta Atete",
    "Norette Atete",
    "Parfait Uhiriwe",
    "Pegdwende Savadogo",
    "Phillip Mulindwa",
    "Prince Mbonyumugisha",
    "Prudence Browns",
    "Remy Intwali",
    "Rwigenza Niyoyandemye",
    "Serein Shima",
    "Sheilla Ruvugabigwi",
    "Solace Afadhali",
    "Sonia Etuhoko",
    "Sonia Uwase",
    "Tabitha Kuir",
    "Thierry Alain Ibyishaka",
    "Thierry Rugira",
    "Uwase Cynthia",
    "Vestine Umukundwa"
];
console.log(contributor.slice(0,3).join(", "), ` and ${contributor.length-3} others`);
